name: Main Build and Deploy

on:

  push:
    branches: [ main ]
  workflow_dispatch:


jobs:

  build:
    name: Build Image
    runs-on: ubuntu-latest

    #permissions to write back to github repo
    permissions:
      contents: write

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get Release Version
        id: semantic
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        with:
          additional_packages: |
            ['@semantic-release/changelog']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: python-helloworld
          IMAGE_TAG: test
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG